sudo: false
language: ruby
before_install:
  - gem update --system
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
addons:
  apt:
    packages:
      - libgsl0-dev
install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
before_script:
  - cp config/database.yml.travis config/database.yml
  - cp config/secrets.yml.example config/secrets.yml
  - mysql -e 'create database aircasting_test;'
  - RAILS_ENV=test bundle exec rake db:migrate
script:
  - yarn test
  - bundle exec rspec --color
