---
:verbose: false
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:concurrency: 15
:queues:
  - [critical, 8]
  - [default, 8]
  - [slow, 2]

:schedule:
  session_stopped_alerts:
    every: '30m'
    class: SessionStoppedAlertsWorker
    queue: critical
