---
:verbose: false
:concurrency: 15
:queues:
  - [critical, 8]
  - [default, 8]
  - [slow, 2]

:schedule:
  session_stopped_alerts:
    every: '30m'
    class: SessionStoppedAlertsWorker
    queue: critical

:schedule:
  open_aq_import_measurements:
    every: '2m'
    class: OpenAqImportMeasurementsWorker
    queue: slow
